export const ActionTypes = {
  LOCATION_DATA_REQUEST: "LOCATION_DATA_REQUEST",
  SET_LOCATION_DATA: "SET_LOCATION_DATA",
  SELECT_LOCATION: "SELECT_LOCATION",
  GET_ATTRACTION_CALL: "GET_ATTRACTION_CALL",
  SET_ATTRACTION: "SET_ATTRACTION",
  GET_ATTRACTION_DETAILS_CALL: "GET_ATTRACTION_DETAILS_CALL",
  SELECT_ATTRACTION: "SELECT_ATTRACTION",
  GET_BOOKINGS_CALL: "GET_BOOKINGS_CALL",
  SET_BOOKINGS: "SET_BOOKINGS",
};
