const obfuscatingTransformer = require("@quinaryio/react-native-obfuscating-transformer");

module.exports = obfuscatingTransformer({
  obfuscatorOptions: {
    compact: true,
    controlFlowFlattening: true,
    controlFlowFlatteningThreshold: 1,
    numbersToExpressions: false,
    simplify: true,
    splitStrings: true,
    stringArrayThreshold: 0.75,
    deadCodeInjection: false,
    debugProtection: false,
    debugProtectionInterval: false,
    disableConsoleOutput: true,
    identifierNamesGenerator: "hexadecimal",
    log: true,
    renameGlobals: false,
    rotateStringArray: true,
    selfDefending: true,
    ignoreRequireImports: true,
    shuffleStringArray: true,
    stringArray: false,
    renameProperties: false,
    unicodeEscapeSequence: false,
    stringArrayEncoding: ["base64"],
    exclude: ["import"],
    stringArrayIndexesType: ["hexadecimal-number"],
    stringArrayIndexShift: true,
    target: "node",
  },
  upstreamTransformer: require("metro-react-native-babel-transformer"),
  filter: (filename) => filename.startsWith("src"),
  emitObfuscatedFiles: false,
  enableInDevelopment: false,
  trace: true,
});
