export const OutletActionTypes = {
  SET_OUTLET_LIST: "SET_OUTLET_LIST",
  SET_HOME_SELECTED_OUTLET: "SET_HOME_SELECTED_OUTLET",
  SET_CURRENT_OUTLET: "SET_CURRENT_OUTLET",
  SET_OUTLET_VALUES: "SET_OUTLET_VALUES",
  SET_MERCHANT_DATA: "SET_MERCHANT_DATA",
  SET_SELECTED_FILTER: "SET_SELECTED_FILTER",
  SET_SELECTED_FILTER_RESET: "SET_SELECTED_FILTER_RESET",
  SET_FAVOURITE_LIST: "SET_FAVOURITE_LIST",

  SET_USER_PROVIDED_CHEERS_CHECK: "SET_USER_PROVIDED_CHEERS_CHECK",
  SET_IS_USER_FILLED_CHEERS_CHECK: "SET_IS_USER_FILLED_CHEERS_CHECK",
  SET_CHEERS_VALUES: "SET_CHEERS_VALUES",

  //saga
  GET_CHEERS_REQUEST: "GET_CHEERS_REQUEST",
  GET_OUTLETS_REQUEST: "GET_OUTLETS_REQUEST",
  GET_OUTLETS_TABS_REQUEST: "GET_OUTLETS_TABS_REQUEST",
  GET_OUTLETS_MAPS_REQUEST: "GET_OUTLETS_MAPS_REQUEST",

  // not persisted
  SET_OUTLETNOTPERSISTED_LIST: "SET_OUTLETNOTPERSISTED_LIST",
  SET_OUTLETNOTPERSISTED_MAP_LIST: "SET_OUTLETNOTPERSISTED_MAP_LIST",
};
