const SEARCH_OUTLET = "SEARCH_OUTLET";
const SEARCH_OUTLET_SUCCESS = "SEARCH_OUTLET_SUCCESS";
const SEARCH_OUTLET_FAILURE = "SEARCH_OUTLET_FAILURE";
const RESET_SEARCH = "RESET_SEARCH";
const SEARCH_ADD_RECENT_QUERY = "SEARCH_ADD_RECENT_QUERY";

export {
  SEARCH_OUTLET,
  SEARCH_OUTLET_SUCCESS,
  SEARCH_OUTLET_FAILURE,
  RESET_SEARCH,
  SEARCH_ADD_RECENT_QUERY,
};
