const PRIMARY_LITE = "PRIMARY_LITE"; // 100
const PRIMARY = "PRIMARY"; // 300
const PRIMARY_BOLD = "PRIMARY_BOLD"; // 500
const PRIMARY_EXTRABOLD = "PRIMARY_EXTRABOLD"; // 700
const PRIMARY_BLACK = "PRIMARY_EXTRA_BOLD"; // 900

export {
  PRIMARY_LITE,
  PRIMARY,
  PRIMARY_BOLD,
  PRIMARY_EXTRABOLD,
  PRIMARY_BLACK,
};
