export const HomeActionTypes = {
  SET_HOME_SECTION: "SET_HOME_SECTION",
  SET_HOME_CATEGORY: "SET_HOME_CATEGORY",
  SET_HOME_CATEGORY_LIST: "SET_HOME_CATEGORY_LIST",
  SET_HOME_VALUES: "SET_HOME_VALUES",
  SET_HOME_MAIN_COVER: "SET_HOME_MAIN_COVER",
  HOME_REQUEST: "HOME_REQUEST",
  LOCATION_LIST_REQUEST: "LOCATION_LIST_REQUEST",
  UPDATE_LAYOUT: "UPDATE_LAYOUT",
  SET_NEAREST_TILES: "SET_NEAREST_TILES",
  HOME_NEAREST_REQUEST: "HOME_NEAREST_REQUEST",
  SET_ANALYTICS_FLAG: "SET_ANALYTICS_FLAG",
};
