export const ActionTypes = {
  SET_MERCHANT_VALUES: "SET_MERCHANT_VALUES",
  SET_SELECTED_OUTLET: "SET_SELECTED_OUTLET",
  SET_SELECTED_OFFER: "SET_SELECTED_OFFER",
  RESET_MERCHANT: "RESET_MERCHANT",
  SET_FAV: "SET_FAV",
  GET_MERCHANT_REQUEST: "GET_MERCHANT_REQUEST",
  REDEEM_OFFER_REQUEST: "REDEEM_OFFER_REQUEST",
};
