export const ActionTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  REGISTRATION_REQUEST: "REGISTRATION_REQUEST",
  FORGOT_PASSWORD_REQUEST: "AUTH_FORGOT_PASSWORD_REQUEST",
  AUTH_UPDATE_RESEND_EMAIL: "AUTH_UPDATE_RESEND_EMAIL",
  AUTH_UPDATE_CAPTCHA_TOKEN: "AUTH_UPDATE_CAPTCHA_TOKEN",
  AUTH_UPDATE_FORCE_LOGIN: "AUTH_UPDATE_FORCE_LOGIN",
  AUTH_UPDATE_LOGIN_DATA: "AUTH_UPDATE_LOGIN_DATA",
  AUTH_UPDATE_ALREADY_LOGIN_DATA: "AUTH_UPDATE_ALREADY_LOGIN_DATA",
  AUTH_UPDATE_REGISTRATION_SUCCESS_MSG: "AUTH_UPDATE_REGISTRATION_SUCCESS_MSG",
  AUTH_UPDATE_LOGIN_SHOW: "AUTH_UPDATE_LOGIN_SHOW",
};
