
name: CI

on:
  push:
    branches:
      - 63772788498625091a79e7f0
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
          java-package: jdk
      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.6
      - uses: actions/checkout@v1
      - name: Install dependencies
        id:   dependencies
        run: |
          yarn install
        continue-on-error: true
      - name: Run Webhook Error For Yarn Dependencies Error
        if:   steps.dependencies.outcome != 'success'
        run: |
          curl -X POST --header "Content-Type: application/json" --data  '{"message":"Error while installing yarn dependencies!"}' https://euthrzapi.etenvbiz.com/mobilebuild/webhook/callback/637b5be2a09ef62e207931d4/error
      - uses: vgaidarji/android-github-actions-build@v1.0.1
        if: steps.dependencies.outcome == 'success'
      - name: Setup cmake 3.19
        uses: jwlawson/actions-setup-cmake@v1.7
        with:
          cmake-version: '3.19.x'
      - name: Setup cmake 3.15
        uses: jwlawson/actions-setup-cmake@v1.7
        with:
          cmake-version: '3.15.x'
      - name: Run Gradle command
        id:   build
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;23.1.7779620" --sdk_root=${ANDROID_SDK_ROOT} && cd ./android && echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p && ENVFILE=.env  ./gradlew clean && ./gradlew assembleRelease --stacktrace
        if: steps.dependencies.outcome == 'success'
        continue-on-error: true
      - name: Run Webhook Success
        if:   steps.build.outcome == 'success' && steps.dependencies.outcome == 'success'
        run: |
            curl -F "file=@./android/app/build/outputs/apk/release/app-release.apk" -X POST  https://euthrzapi.etenvbiz.com/mobilebuild/webhook/callback/637b5be2a09ef62e207931d4
      - name: Run Webhook Error
        if:   steps.build.outcome != 'success' && steps.dependencies.outcome == 'success'
        run: |
          curl -X POST  https://euthrzapi.etenvbiz.com/mobilebuild/webhook/callback/637b5be2a09ef62e207931d4/error
